language: node_js
node_js:
  - lts/*
install:
  - yarn install
script:
  - yarn docs:build 
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: 0ea380c9cfe44edc4cca1bd9619a11c8974e2692
  keep_history: true
  on:
    branch: master