language: node_js
node_js:
  - lts/*
install:
  - yarn install 
script:
  - yarn docs:build
deploy:
  provider: pages
  local_dir: docs/.vuepress/dist
  github_token: $GITHUB_TOKEN 
  keep_history: true
