language: node_js
node_js:
  - 16
install:
  - npm ci
script:
  - npm run docs:build
deploy:
  provider: pages
  target_branch: hostgator
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
